document.write("Hello, World");
var A = "This is a string";
document.write(A);
var B = "This is a String 2";
window.alert(B);
document.write("This is test \"String\" for the assignment");
document.write("Combining this string with " + "next string");
var B = "Concatenated" + " String";
document.write(B);
var name ="Alex John", address="631, unknown street", phoneNumber="6479999999";
document.write(phoneNumber);
var exp = 3+3;
document.write(exp);